import { NextRequest, NextResponse } from 'next/server';
import { getAllFoodLogs, createFoodLogEntry } from '@services/foodLog';

export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ username: string }> }
) {
  const { username } = await params;
  const foodLogs = await getAllFoodLogs(username);
  return NextResponse.json(foodLogs);
}

export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ username: string }> }
) {
  try {
    const { username } = await params;
    const body = await req.json();
    // Add userID (logID is auto-generated by database)
    const foodLogData = {
      userID: username,
      foodID: body.foodID,
      servingSize: body.servingSize,
    };
    const newFoodLog = await createFoodLogEntry(foodLogData);
    return NextResponse.json(newFoodLog);
  } catch (error) {
    console.error('Error creating food log:', error);
    return NextResponse.json(
      { error: 'Failed to create food log entry' },
      { status: 500 }
    );
  }
}